"""
Multilingual LLM Client — Hackathon IABiomed 2026 — SINAI-UJA

Client for the multilingual model (gemma-4-31B-it) in charge of:
  1. Translating the content of the humanized report (Spanish PDF from Recog)
     to the language requested by the user.
  2. Filling the LaTeX template with the translated content.

Connects to the same OpenAI-compatible endpoint as the error agent,
but uses a different model configured via MULTILINGUAL_MODEL_NAME.
"""

import re
from typing import Optional

try:
    from openai import OpenAI
except ImportError:  # pragma: no cover
    OpenAI = None

from utils.config import load_config
from utils.logging_config import get_logger


SUPPORTED_LANGUAGES = {
    "es": "Castellano / Español",
    "ca": "Catalán",
    "va": "Valenciano",
    "gl": "Gallego",
    "eu": "Euskera / Vasco",
}


def _get_multilingual_client() -> Optional[OpenAI]:
    if OpenAI is None:
        return None
    cfg = load_config()
    return OpenAI(api_key=cfg.openai_api_key, base_url=cfg.openai_base_url)


def _strip_markdown_fences(text: str) -> str:
    """
    Removes markdown code fences that some LLMs add around LaTeX output.
    e.g.: ```latex\\n...\\n``` → ...
    """
    # Remove ```latex or ``` at start and ``` at end
    text = text.strip()
    # Match optional language tag after the opening fence
    match = re.match(r"^```[a-zA-Z]*\n?(.*?)```\s*$", text, re.DOTALL)
    if match:
        return match.group(1).strip()
    # Fallback: just strip a leading ```latex or ``` line and trailing ``` line
    lines = text.splitlines()
    if lines and re.match(r"^```", lines[0]):
        lines = lines[1:]
    if lines and lines[-1].strip() == "```":
        lines = lines[:-1]
    return "\n".join(lines).strip()


class MultilingualClient:
    """
    Client for multilingual medical translation using an OpenAI-compatible LLM.
    """

    def __init__(self, api_key: str, base_url: str, model_name: str):
        self.client = OpenAI(api_key=api_key, base_url=base_url)
        self.model_name = model_name

    def translate_latex(
        self,
        latex_template: str,
        source_text: str,
        target_lang: str,
        logger=None,
    ) -> str:
        """
        Translates the content of the report to the target language and returns
        the complete LaTeX code ready to compile.

        Args:
            latex_template: Base LaTeX code (template).
            source_text: Text extracted from the Spanish PDF generated by Recog.
            target_lang: ISO code of the target language (ca, gl, eu).
            logger: Optional logger to record tokens/progress.

        Returns:
            Complete translated LaTeX code.
        """
        lang_name = SUPPORTED_LANGUAGES.get(target_lang, target_lang)

        system_prompt = (
            f"Eres un traductor médico experto especializado en {lang_name}. "
            "Tu tarea es traducir informes médicos humanizados al lenguaje del paciente "
            f"en {lang_name}, manteniendo la estructura, tono empático y claridad. "
            "Devuelve ÚNICAMENTE el código LaTeX completo listo para compilar. "
            "No añadas explicaciones ni markdown fuera del código LaTeX."
        )

        user_prompt = (
            f"Traduce TODO el contenido del siguiente informe médico al {lang_name}.\n\n"
            "=== TEXTO DEL INFORME (español) ===\n"
            f"{source_text}\n\n"
            "=== PLANTILLA LaTeX ===\n"
            f"{latex_template}\n\n"
            "=== INSTRUCCIONES ===\n"
            "1. Traduce TODOS los títulos de secciones y el texto explicativo.\n"
            "2. Mantén exactamente la misma estructura de secciones de la plantilla.\n"
            "3. Mantén SIEMPRE \\usepackage[spanish]{babel} en el documento LaTeX, no cambies el idioma del paquete babel (debe seguir siendo spanish) para evitar fallos de compilación en el servidor.\n"
            "4. Devuelve el código LaTeX COMPLETO y listo para compilar con pdflatex.\n"
            "5. No omitas ninguna sección. No añadas comentarios fuera del LaTeX."
        )

        response = self.client.chat.completions.create(
            model=self.model_name,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0.2,
            max_tokens=8192,
        )

        msg = response.choices[0].message
        raw = msg.content or ""
        if not raw:
            raw = getattr(msg, "reasoning", "") or ""

        usage = getattr(response, "usage", None)

        if logger and usage:
            logger.info(
                "   Tokens usados (traducción): prompt=%s, completion=%s",
                getattr(usage, "prompt_tokens", "?"),
                getattr(usage, "completion_tokens", "?"),
            )

        # Post-processing: strip markdown code fences if the model wrapped the output
        raw = _strip_markdown_fences(raw)

        # Post-processing: Force babel to always use 'spanish' option to prevent missing .ldf errors in pdfLaTeX.
        # The document text is already translated by the LLM, so pdfLaTeX compiles and renders it correctly.
        raw = re.sub(r"\\usepackage\[[^\]]*\]\{babel\}", r"\\usepackage[spanish]{babel}", raw)

        # Post-processing: Escape raw underscores (_) as (\_) to avoid LaTeX math-mode parsing errors on PII placeholders.
        raw = re.sub(r"(?<!\\)_", r"\\_", raw)

        # Post-processing: Sanitize characters to remove Japanese or other non-western scripts that crash pdfLaTeX.
        raw = _sanitize_latex_chars(raw)

        return raw.strip()

def _sanitize_latex_chars(text: str) -> str:
    """
    Keeps only characters supported by pdfLaTeX with standard Western European encodings
    (ASCII, Latin Extended blocks, common punctuation, Euro symbol) and strips the rest
    (like CJK, Cyrillic, etc.) to prevent compilation crashes.
    """
    sanitized = []
    for char in text:
        cp = ord(char)
        if cp <= 0x024F:  # ASCII + Latin Extended-A & B
            sanitized.append(char)
        elif 0x2000 <= cp <= 0x206F:  # General punctuation (curly quotes, dashes)
            sanitized.append(char)
        elif cp == 0x20AC:  # Euro symbol
            sanitized.append(char)
    return "".join(sanitized)

    @staticmethod
    def get_language_name(code: str) -> str:
        return SUPPORTED_LANGUAGES.get(code, code)


def create_multilingual_client() -> MultilingualClient:
    cfg = load_config()
    return MultilingualClient(
        api_key=cfg.openai_api_key,
        base_url=cfg.openai_base_url,
        model_name=cfg.multilingual_model_name,
    )
